name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's missing today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Core (content, routing, config)
        - CLI (dev/build commands)
        - Components (UI components)
        - Documentation
        - Other
    validations:
      required: true
